import { Rocket, Database, Smartphone } from 'lucide-react'
import { supabase } from './supabase'

const APP_NAME = "leetcode-trainer-pro"
const DESCRIPTION = "LeetCode Top Interview 150 \uae30\ubc18 \ucf54\ub529 \ud14c\uc2a4\ud2b8 \uc5f0\uc2b5 \uc571. \uac1c\ub150 \ud559\uc2b5(Easy/Medium \ud398\uc5b4), \uc54c\uace0\ub9ac\uc998 \uc2dc\uac01\ud654, \ub79c\ub364 \uc2e4\uc804 \ubb38\uc81c \ubc0f \ud78c\ud2b8 \uc81c\uacf5."

const features = [
  ['Telegram first', '핸드폰에서 요청하고 바로 수정/배포하는 흐름을 전제로 만든 앱입니다.', Smartphone],
  ['Vercel deploy', 'GitHub push 이후 Vercel에서 웹 앱으로 배포됩니다.', Rocket],
  ['Supabase ready', '환경변수가 있으면 Supabase 클라이언트가 즉시 준비됩니다.', Database],
]

export default function App() {
  return (
    <main className="shell">
      <section className="panel">
        <p className="eyebrow">Generated by Telegram Claude Bot</p>
        <h1>{APP_NAME}</h1>
        <p className="lead">{DESCRIPTION}</p>
        <div className="status">
          <span className={supabase ? 'dot on' : 'dot'} />
          <span>{supabase ? 'Supabase connected' : 'Supabase env pending'}</span>
        </div>
      </section>

      <section className="grid">
        {features.map(([title, body, Icon]) => (
          <article className="card" key={title}>
            <Icon size={22} strokeWidth={1.8} />
            <h2>{title}</h2>
            <p>{body}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
